--- #YAML:1.0
name: Video-ZVBI
abstract: Interface to the Zapping VBI decoder library
version: 1.1.0
author:
  - T. Zoerner <tomzo@users.sourceforge.net>
license: GPL
distribution_type: module
keywords:
  - video
  - DVB
  - teletext
  - videotext
  - closed caption
  - WSS
  - VPS
  - VBI
  - capture
  - decoder
  - libzvbi
  - ETSI
requires:
  perl: 5.7.1
recommends:
  Tk: 800
excludes_os: MSWin32
no_index:
  directory:
    - examples
resources:
  license: http://www.gnu.org/licenses/
  homepage: https://github.com/tomzox/Perl-Video-ZVBI
